### ISSUE TITLE
Local hosting minor/medium bugs

### ISSUE THREAD

**Issue by mut3** [dougbtv/bowline#12]
## Preface
I understand that Bowline is very Beta and I felt that these issues were outside the scope of my mongo fork.

These are a few errors I encounter with a [fresh clone as of right now](https://github.com/dougbtv/bowline/commit/1163e33f5098ba7e3485806aec2c7a4bd10c0a3a)

On a centOS 7 box that I am accessing from another machine on the same internal network by pointing at its IP, this brings me to the dockertest.com bowline page. The only setup I did on the server was run `build_it.sh` and `run_it.sh`.

## Errors

Line 37 of `build_it.sh` creates this at run:
```
Starting mongo client
2015-06-03T14:18:45.405+0000    Failed: open /exampledata/json/releases.json: permission denied
2015-06-03T14:18:45.405+0000    imported 0 documents
2015-06-03T14:18:45.414+0000    Failed: open /exampledata/json/users.json: permission denied
2015-06-03T14:18:45.414+0000    imported 0 documents
Cleaning up all containers....
```

When connecting to the web interface through a browser (Chrome Version 43.0.2357.81 m):
* None of the links in the navbar function, I am however able to move around the site by pointing at the proper URLs
* No login/account functionality, including with bowlineadmin:bowline. I feel that this one is likely tied to the errors during `build_it.sh`
* socket.io errors out with a 502
* A lot of placeholder/variable markers that still look like {{this}} and aren't properly working. I assume this is because of noted socket.io crash

I felt like I should note these outside of my [original issue](https://github.com/dougbtv/bowline/issues/9) and its resulting [pull request](https://github.com/dougbtv/bowline/pull/10) as they were not within the scope of the issue and beyond a successfully running Bowline app I did not know how well a local hosted copy should work.

**Comment by dougbtv** [comment]
Excellent documentation of the issues. I'll run through bringing up a fresh clone and work through these. There are definitely some rough edges on bringing it up for the first time, so I'll take a look in the next few days and figure out what's up. Likely, a big fat javascript crash is showing the AngularJS `{{stuff}}` which usually means Angular got cut off at the knees.

Definitely beyond the scope, appreciate what you'd done before, I'll take a look at those to get it back to a nominal state on a fresh clone. 

...Likely too I need to look at how the registry comes up, which is the diciest part, too.

**Comment by dougbtv** [comment]
Hrmm, I didn't replicate the error during `build_it.sh`, here's [my entire output](http://www.pasteall.org/58798). Under Fedora 21 with `Docker version 1.6.0, build 350a636/1.6.0`

Granted, I did run it as root. But, I'm guessing if you got that far in the build, your docker permissions are definitely on point, no matter how you ran it.

Here's my output from that phase:

    Running mongo for preload...
    65cddf981ba3a47ffd69cdc1862e034c86a9a63e509e1644ebf938e6b245f32c
    Starting mongo client
    2015-06-03T15:51:40.912+0000    connected to: mongo
    2015-06-03T15:51:40.946+0000    imported 3 documents
    2015-06-03T15:51:40.972+0000    connected to: mongo
    2015-06-03T15:51:41.013+0000    imported 2 documents

That being said, I might come back to this one and try to replicate it, and I'll move onto the rest of the show-stoppers.

**Comment by dougbtv** [comment]
Making some progress, I think I made a copy-pasta error in the `example.config.json` and looks like a line was wrong for the mongo config. Also, the `example.config.json` was missing during the build.

So, I've fixed that up in the develop branch. 

Still on the punch-list:
* replicate error pre-loading mongo data
* noticed funky error pulling up sample data from github

-------------
From the logs when it crashed:

```
[root@localhost bowline]# docker logs bowline
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Invalid mongodb uri. Must begin with "mongodb://"
  Received: mongo://mongo/bowline
    at muri (/bowline/node_modules/mongoose/node_modules/muri/lib/index.js:28:11)
    at NativeConnection.Connection.open (/bowline/node_modules/mongoose/lib/connection.js:205:16)
    at Mongoose.connect (/bowline/node_modules/mongoose/lib/index.js:223:15)
    at /bowline/bowline.js:33:11
    at /bowline/library/Options.js:162:4
    at /bowline/library/Options.js:31:7
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
error: Forever detected script exited with code: 8
```

**Comment by mut3** [comment]
@dougbtv looks like there was a reason I hadn't changed that line. Whoops. reverting the change i suggested to the `includes/example.config.json` may resolve that one.

**Comment by mut3** [comment]
after [this commit](https://github.com/mut3/bowline/commit/57827652c87c13f18a5d2d627bbec09992895d85), where i did what the error told us and changed the address back to `mongodb://mongo/bowline`, I did not get that error.

```
[2015-06-03T17:35:58.682Z]  INFO: bowline/17 on a4fef1524cbf:  (label=mongo_connect)
    
    --
    content: {
      "server": "mongodb://mongo/bowline"
    }
```

**Comment by mut3** [comment]
and just for fun I tried it with the full old connect string 
```
 "MONGO_CONNECT_STRING": "mongodb://mongodb/bowline"
```
and got
```
MONGO CONNECTION ERROR:  { server: 'mongodb://mongodb/bowline' }
```
so

```
"MONGO_CONNECT_STRING":"mongodb://mongodb/bowline"
```

is our winner, sorry about creating that bug.

**Comment by dougbtv** [comment]
Bah no worries! I'm glad this gives me an opportunity to run through the initial spin up of running it locally, still some stuff there that I might not have noticed without the bug! Helps in the end.

**Comment by mut3** [comment]
That also seems to have resolved the broken Angular.js

Now I'll see if I can get some detailed error logs on the data preload.

**Comment by mut3** [comment]
@dougbtv  or fix it.

https://github.com/mut3/bowline/commit/dab76b12b38e4458c3b8be6140ca98b755629566

I guess I missed a --privileged flag because it didn't cause a full failure.

This also fixed my login issue. I was able to login as bowlineadmin:bowline.

The socket.io errors are probably due to the network I'm working in right now.


### Conclusion

I'm going to close this because it looks like everything I reported above was due to stuff I either broke or failed to fix in my mongo upgrade.

**Comment by dougbtv** [comment]
Thanks mut3, damn, appreciate your thoroughness! socket.io can be touchy, happy to take a look if you're still experiencing problems, but, the whole app (including socket.io) was definitely borked at first due to bowline.js not running when it couldn't connect to mongo.

Appreciate you taking the time to try out bowline, helps me out, for sure.

**Comment by mut3** [comment]
@dougbtv I think I'll be at the LabB open hours tomorrow night, hope to see you there.

And if I had been more thorough the first time these bugs wouldn't exist. Thanks for being extremely responsive to my issues/pull request.

**Comment by dougbtv** [comment]
Thank you too! I'm going to try to make it. Things are a bit up in the air with work, so... only like a 50/50 shot I can make it, but, I'll ping you if I can't, and then maybe another time (pretty cool crew there, for sure).
