### ISSUE TITLE
Self host git hook url

### ISSUE THREAD

**Issue by mut3** [dougbtv/bowline#13]
I noticed that when I go to create a knot on my self-hosted Bowline the git hook points at bowline.io instead of the domain I'm on.

**Comment by dougbtv** [comment]
Ooops, good eye. I'll take a look. 

@mut3 -- also fwiw, I don't think I'm going to make it to lab b tonight with what I've got going on, sorry! At any rate, hopefully get to catch up another time.

**Comment by dougbtv** [comment]
Ok, I think I cooked this in as an environment variable in the front-end, which... Isn't really ideal.

Here's where I found it: https://github.com/dougbtv/bowline/blob/master/www/Gruntfile.js#L356-L370

I think I'll make it configurable from the back-end, and let it read from `config.json` and pass it along to the front-end.

**Comment by mut3** [comment]
That makes sense, having the admin running the server define the domain is much easier than auto-detecting something.

**Comment by dougbtv** [comment]
Alright -- you'll find a new parameter in `example.config.json` called `bowline_domain` which will let you set it. That's in master, as well as the commits from your PR to develop later last week.

Good eye on this one! 

-Doug

**Comment by mut3** [comment]
Super, I'll keep an eye as more features of bowline get fleshed out, this project has the potential to be very useful.

Cheers
