### ISSUE TITLE
deprecated mongodb

### ISSUE THREAD

**Issue by mut3** [dougbtv/bowline#9]
bowline is currently building and relying on the deprecated `dockerfile/mongodb' 
https://registry.hub.docker.com/u/deprecateddockerfile/mongodb/

mongo has moved to 'library/mongo' and command syntax has changed somewhat
https://registry.hub.docker.com/_/mongo/

i forked bowline and am currently working on updating all mongo related commands in the build and run scripts to use the new commands and point at the right repo.
https://github.com/mut3/bowline

**Comment by dougbtv** [comment]
@mut3 -- thank you! I'll happily take a PR if you're able to get it to run, also... let me know if you run into anything.

...I got the notices from Dockerhub about the dockerfile/* repos being deprecated, but, I hadn't moved on that yet. 

Appreciate the eyeballs / heads-up & the fork.

**Comment by mut3** [comment]
Issue resolved and pulled.
https://github.com/dougbtv/bowline/pull/10
